name: Java CI with Maven and JaCoCo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: 'success'

      - name: Change directory to math
        run: cd math/src/test/java/com/example/math/math

      - name: Install JaCoCo
        run: wget -q https://repo1.maven.org/maven2/org/jacoco/jacoco-maven-plugin/0.8.7/jacoco-maven-plugin-0.8.7.jar -P /tmp/jacoco/ && echo 'Installation completed.'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Run tests with JUnit
        run: mvn test

      - name: Generate JaCoCo report
        run: mvn jacoco:report
