name: Java CI with Maven and JaCoCo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Change to project directory
      run: cd math/src/test/java/com/example/math/math/MathCalculatorTest.java

    - name: Build with Maven
      run: mvn -B clean package

    - name: Run tests with Maven
      run: mvn test

    - name: Generate JaCoCo report
      run: mvn jacoco:report

    - name: Upload JaCoCo report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: WorkflowSpringProject/WorkflowSpringProject/target/site/jacoco/index.html
